### ISSUE TITLE
Inline SDL descriptions causes errors

### ISSUE THREAD

**Issue by joshprice** [APIs-guru/graphql-faker#41]
GraphQL SDL now supports inline descriptions as documentation (http://facebook.github.io/graphql/draft/#sec-Descriptions), but this throws errors in the editor.

This looks to be an issue with the fork and branch (https://github.com/apis-guru/graphql-js/tree/directives-fork-dist) that `graphql-faker` relies on in https://github.com/APIs-guru/graphql-faker/blob/master/package.json#L48).

Currently that branch is > 500 commits behind. Is there anything preventing this from being updated to the latest?

**Comment by IvanGoncharov** [comment]
> Currently that branch is > 500 commits behind.

Yeah I know, ~50 of those are mine 😄 

> Is there anything preventing this from being updated to the latest?

The main issue is that this project based on my first implementation of directives support in `graphql-js` which was rejected. After that, I managed to push very basic support for directives at https://github.com/graphql/graphql-js/pull/746

Initially, I planned to push all necessary functionality to `graphql-js` and when to rewrite this project to remove all hacks and workarounds. But it seems it taking to much time and missing support for new SDL syntax is a real issue so I think the time has come.

I would try to update it to vanilla `v0.10.4` since it's the first having at least some directive support: https://github.com/graphql/graphql-js/releases/tag/v0.10.4

**Comment by IvanGoncharov** [comment]
@joshprice I finally migrated away from forked graphql and released 2.0.0-rc.1 📦 with this change.
If you have time can you please test it?
