### ISSUE TITLE
Extend API Graphql

### ISSUE THREAD

**Issue by joserochadocarmo** [APIs-guru/graphql-faker#8]
I'm new to graphql, I really liked this project!! But, i've been thinking outside the box, do you think it's possible for a graphql server to inherit other graphql? Like this:

graphql-no-faker-master --extend http://graph-project-01, http://graph-project-02, http://graph-project-03 ....

I work in an unversity and this would be great, for team independence and data integration.

**Comment by IvanGoncharov** [comment]
@joserochadocarmo Interesting idea 👍 

> do you think it's possible for a graphql server to inherit other graphql?

There are some problems, for example, name-clash of type and field names since GraphQL doesn't have the concept of namespaces. But it's definitely possible.

However, it's definitely outside of scope for graphql-faker but I encourage you to try to implement this idea. You can reuse big chunk of code from graphql-faker: https://github.com/APIs-guru/graphql-faker/blob/master/src/proxy.ts
